/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'

const TermsAndConditionsLazyRouteImport = createFileRoute(
  '/terms-and-conditions',
)()
const RegisterLazyRouteImport = createFileRoute('/register')()
const PrivacyPolicyLazyRouteImport = createFileRoute('/privacy-policy')()
const LoginLazyRouteImport = createFileRoute('/login')()
const ForgotPasswordLazyRouteImport = createFileRoute('/forgot-password')()
const DisclaimerLazyRouteImport = createFileRoute('/disclaimer')()
const CookiePolicyLazyRouteImport = createFileRoute('/cookie-policy')()
const IndexLazyRouteImport = createFileRoute('/')()
const CoursesIndexLazyRouteImport = createFileRoute('/courses/')()
const CoursesSlugLazyRouteImport = createFileRoute('/courses/$slug')()
const AuthProfileLazyRouteImport = createFileRoute('/_auth/profile')()
const AuthPlayerLazyRouteImport = createFileRoute('/_auth/player')()

const TermsAndConditionsLazyRoute = TermsAndConditionsLazyRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/terms-and-conditions.lazy').then((d) => d.Route),
)
const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const PrivacyPolicyLazyRoute = PrivacyPolicyLazyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ForgotPasswordLazyRoute = ForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)
const DisclaimerLazyRoute = DisclaimerLazyRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/disclaimer.lazy').then((d) => d.Route))
const CookiePolicyLazyRoute = CookiePolicyLazyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookie-policy.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CoursesIndexLazyRoute = CoursesIndexLazyRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/courses/index.lazy').then((d) => d.Route))
const CoursesSlugLazyRoute = CoursesSlugLazyRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/courses/$slug.lazy').then((d) => d.Route))
const AuthProfileLazyRoute = AuthProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/profile.lazy').then((d) => d.Route))
const AuthPlayerLazyRoute = AuthPlayerLazyRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/player.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cookie-policy': typeof CookiePolicyLazyRoute
  '/disclaimer': typeof DisclaimerLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/register': typeof RegisterLazyRoute
  '/terms-and-conditions': typeof TermsAndConditionsLazyRoute
  '/player': typeof AuthPlayerLazyRoute
  '/profile': typeof AuthProfileLazyRoute
  '/courses/$slug': typeof CoursesSlugLazyRoute
  '/courses/': typeof CoursesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cookie-policy': typeof CookiePolicyLazyRoute
  '/disclaimer': typeof DisclaimerLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/register': typeof RegisterLazyRoute
  '/terms-and-conditions': typeof TermsAndConditionsLazyRoute
  '/player': typeof AuthPlayerLazyRoute
  '/profile': typeof AuthProfileLazyRoute
  '/courses/$slug': typeof CoursesSlugLazyRoute
  '/courses': typeof CoursesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/_auth': typeof AuthRouteWithChildren
  '/cookie-policy': typeof CookiePolicyLazyRoute
  '/disclaimer': typeof DisclaimerLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/register': typeof RegisterLazyRoute
  '/terms-and-conditions': typeof TermsAndConditionsLazyRoute
  '/_auth/player': typeof AuthPlayerLazyRoute
  '/_auth/profile': typeof AuthProfileLazyRoute
  '/courses/$slug': typeof CoursesSlugLazyRoute
  '/courses/': typeof CoursesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/disclaimer'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms-and-conditions'
    | '/player'
    | '/profile'
    | '/courses/$slug'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/disclaimer'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms-and-conditions'
    | '/player'
    | '/profile'
    | '/courses/$slug'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/cookie-policy'
    | '/disclaimer'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms-and-conditions'
    | '/_auth/player'
    | '/_auth/profile'
    | '/courses/$slug'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthRoute: typeof AuthRouteWithChildren
  CookiePolicyLazyRoute: typeof CookiePolicyLazyRoute
  DisclaimerLazyRoute: typeof DisclaimerLazyRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  PrivacyPolicyLazyRoute: typeof PrivacyPolicyLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  TermsAndConditionsLazyRoute: typeof TermsAndConditionsLazyRoute
  CoursesSlugLazyRoute: typeof CoursesSlugLazyRoute
  CoursesIndexLazyRoute: typeof CoursesIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/player': {
      id: '/_auth/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof AuthPlayerLazyRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthPlayerLazyRoute: typeof AuthPlayerLazyRoute
  AuthProfileLazyRoute: typeof AuthProfileLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPlayerLazyRoute: AuthPlayerLazyRoute,
  AuthProfileLazyRoute: AuthProfileLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthRoute: AuthRouteWithChildren,
  CookiePolicyLazyRoute: CookiePolicyLazyRoute,
  DisclaimerLazyRoute: DisclaimerLazyRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  TermsAndConditionsLazyRoute: TermsAndConditionsLazyRoute,
  CoursesSlugLazyRoute: CoursesSlugLazyRoute,
  CoursesIndexLazyRoute: CoursesIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
